# Generated by Django 3.2.9 on 2021-11-30 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_forum', '0002_auto_20211129_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForumSignup',
        ),
    ]
