# Generated by Django 3.2.9 on 2021-11-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student_forum', '0003_delete_forumsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(blank=True, max_length=70, unique=True)),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
